### ISSUE TITLE
Example scripts

### ISSUE THREAD

**Issue by 0xorial** [Vilsol/go-mlog#1]
Absolutely awesome project!
It would be helpful to have a few examples. They would help to see how to use the game API easier, and help those not very familiar with go.

**Comment by Vilsol** [comment]
Good idea, I will probably make some examples on the wiki

**Comment by Vilsol** [comment]
@0xorial I have added a few examples on the wiki, is there anything else unclear about how to use it?

https://github.com/Vilsol/go-mlog/wiki/Examples

**Comment by 0xorial** [comment]
Looks amazing!

**Comment by LargePrime** [comment]
can you add the use of control to one of the examples?
