### ISSUE TITLE
about use "Processor Variables and Constants" in IDE

### ISSUE THREAD

**Issue by wu452148993** [Vilsol/go-mlog#4]
hi,I saw "Processor Variables and Constants" variable changed to SpecialVar(string) type,that could lead to compilation warning when written code in IDE.
Example:
![image](https://user-images.githubusercontent.com/38494302/113725082-8ec82e80-9725-11eb-9971-8543d94c131d.png)
![image](https://user-images.githubusercontent.com/38494302/113725120-9a1b5a00-9725-11eb-8cdb-a2f8297891f2.png)
In my opinion, we should use TYPE to limit the parameter type of the incoming function, so that we can detect the TYPE ERROR in our code by IDA.
At present, the only way I can think of is to separate the type field from the conversion field. I hope to find a better way, because my method seems a little stupid.lol

**Comment by Vilsol** [comment]
Good catch! I will change how these constants get registered and typed.

**Comment by Vilsol** [comment]
This issue should now be resolved from release v0.0.18.

It also introduced a new method for referencing buildings, now you are required to use `m.B("message1")` or the like, when you are referencing a building. That will get inlined into the function without adding an additional step.
