### ISSUE TITLE
"Therapist" example not working

### ISSUE THREAD

**Issue by sindriing** [Vilsol/go-mlog#8]
Trying to transcode the "Therapist" example fails with the following error message

`error at 282: cannot use "@this" (constant of type string) as interface{GetHealth() int; GetItemCapacity() int; GetName() string; GetRotation() float64; GetShootX() float64; GetShootY() float64; GetTotalItems() int; GetX() float64; GetY() float64; IsShooting() bool} value in argument to m.Sensor: missing method GetHealth`

The following modification on lines [15-17] transpiles and should retain the desired behaviour. 

```
        if health == maxHealth {
		print("Home")
		homeX := float64(m.ThisX)
		homeY := float64(m.ThisY)
		m.UnitApproach(homeX, homeY, 10)
	}
```

I tried to edit the wiki myself but I cannot figure out a good way to do so. Seems like public access to the wiki isn't allowed and a "fork + pull-request" of the repo won't work since the wiki isn't forked along with the rest of the repo.

**Comment by Vilsol** [comment]
Thanks for pointing this out! I have fixed up the script and noticed a typo bug! The wiki is now updated (and even optimized a little)
