### ISSUE TITLE
[Feature] Go "math" module mappings

### ISSUE THREAD

**Issue by nbrugger-tgm** [Vilsol/go-mlog#9]
Some operations from mlog are not useable since the mapping of the regarding math functions is missing

example:
MLOG:
```asm
op abs result a b
op len result a b
op sqrt result a b
op max result a b
op min result a b
op angle result a b
```
Go-mlog:
```go
import (
	"github.com/Vilsol/go-mlog/m"
	"math"
)
func main(){
  result := math.Abs(a)
  result = m.vectorLen(a,b)
  result = math.Sqrt(a)
  result = math.Max(a,b)
  result = math.Min(a,b)
  result = m.vectorAngle(a,b)
}
```
> This are not all missing mappings but the imo most common ones that are missing

**Comment by Vilsol** [comment]
Thanks, this is a known issue, I will implement them in the next release later today!

**Comment by Vilsol** [comment]
Should be fixed in latest release
